; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

; ------------------------------------------------------------
; Raspberry Pi native Linux controller
; ------------------------------------------------------------
[env:raspberry_pi_controller]
platform = native

build_flags =
    -std=c++17
    -I ../shared
    -D LIBGPIOD_V2=1
    -D PI_BAKE_BUZZER_GPIO=24
    -D PI_BAKE_BUZZER_MS=350
    -lmosquitto
    -lgpiod

; __Raspberry Pi Setup__
; 
; Run these commands on the Raspberry Pi:
;
;   ```
;   sudo apt update
;   sudo apt install -y mosquitto mosquitto-clients libmosquitto-dev libgpiod-dev
;   ```
;
; Enable and start Mosquitto:
;
;   ```
;   sudo systemctl enable mosquitto
;   sudo systemctl start mosquitto
;   ```
;
; Check status:
;
;   ```
;   sudo systemctl status mosquitto
;   ```
;
; Press q to exit.
; 
; Create the audio folder:
;
;   ```
;   mkdir -p ~/escape-room/assets/audio
;   ```
;
; Place the audio files here:
;
;   ```
;   /home/admin/escape-room/assets/audio/crashing_plates.m4a
;   /home/admin/escape-room/assets/audio/buzzer.mp3
;   /home/admin/escape-room/assets/audio/look-behind-you.mp3
;   /home/admin/escape-room/assets/audio/yeah-you-did-it.mp3
;   /home/admin/escape-room/assets/audio/bake_at_350.wav
;   ```
;
; From the project folder on the Raspberry Pi, run:
;
;   ```
;   pio run -e raspberry_pi_controller
;   pio run -e raspberry_pi_controller -t exec
;   ```
; You should see the following:
;
;  ```
;   pio run -e raspberry_pi_controller
;   Escape Room Raspberry Pi Game Controller
;   Broker: localhost:1883
;   Topic: escape/puzzle/copper/solved
;   Waiting for puzzle events...
;   Connected to MQTT broker.
;   Subscribed to topic: escape/puzzle/copper/solved
;   ```
;
; Then open another terminal on the pi and run:
;
;   ```
;   mosquitto_sub -h localhost -t "escape/puzzle/copper/solved" -m "Manual Test"
;   ```
;
; The running C++ controller should print:
;
;   ```
;   MQTT message received.
;   Topic: escape/puzzle/copper/solved
;   Payload: manual test
;   Puzzle solved event received!
;   ```
;
; If the audio files exist and ffmpeg is installed, the controller should try to play them.

