; PlatformIO Project Configuration File

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipicow
framework = arduino
board_build.core = earlephilhower

monitor_speed = 115200
upload_protocol = picotool

lib_deps =
    knolleary/PubSubClient@^2.8

build_flags =
    -D WIFI_SSID=\"EscapeRoom\"
    -D WIFI_PASS=\"BakeAt350\"
    -D MQTT_BROKER=\"10.42.0.1\"
    -D MQTT_BROKER_PORT=1883
    -D MQTT_CLIENT_ID=\"pico3-painting-rotation\"
