; PlatformIO Project Configuration File

[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = rpipicow
framework = arduino
board_build.core = earlephilhower

monitor_speed = 115200
upload_protocol = picotool
extra_scripts = pre:../tools/platformio_pico_wifi.py

lib_deps =
    knolleary/PubSubClient@^2.8

build_flags =
    -D MQTT_CLIENT_ID=\"pico2-copper-final-piece\"
