#ifndef ESCAPE_ROOM_STATE_H
#define ESCAPE_ROOM_STATE_H

enum class RoomState {
    WAITING_FOR_CUBBY_APPROACH,
    CUBBY_APPROACH_DETECTED,
    FIRST_CUBBY_LIT,
    COPPER_PUZZLE_ACTIVE,
    COPPER_PUZZLE_COMPLETE,
    BOTTLE_LOCK_STAGE,
    PADLOCK_BOX_STAGE,
    RFID_STAGE,
    PAINTING_ROTATION_ACTIVE,
    PAINTING_ROTATION_COMPLETE,
    CRASHING_PLATES_PLAYED,
    SMART_FILM_REVEALED,
    COLOR_BUTTON_SEQUENCE_ACTIVE,
    COLOR_BUTTON_SEQUENCE_COMPLETE,
    DISPLAY_BAKE_350,
    OVEN_KNOB_ACTIVE,
    OVEN_TARGET_REACHED,
    ELECTROMAGNETIC_LOCK_RELEASED,
    ROOM_KEY_AVAILABLE,
};

inline const char* roomStateName(RoomState state) {
    switch (state) {
        case RoomState::WAITING_FOR_CUBBY_APPROACH: return "WAITING_FOR_CUBBY_APPROACH";
        case RoomState::CUBBY_APPROACH_DETECTED: return "CUBBY_APPROACH_DETECTED";
        case RoomState::FIRST_CUBBY_LIT: return "FIRST_CUBBY_LIT";
        case RoomState::COPPER_PUZZLE_ACTIVE: return "COPPER_PUZZLE_ACTIVE";
        case RoomState::COPPER_PUZZLE_COMPLETE: return "COPPER_PUZZLE_COMPLETE";
        case RoomState::BOTTLE_LOCK_STAGE: return "BOTTLE_LOCK_STAGE";
        case RoomState::PADLOCK_BOX_STAGE: return "PADLOCK_BOX_STAGE";
        case RoomState::RFID_STAGE: return "RFID_STAGE";
        case RoomState::PAINTING_ROTATION_ACTIVE: return "PAINTING_ROTATION_ACTIVE";
        case RoomState::PAINTING_ROTATION_COMPLETE: return "PAINTING_ROTATION_COMPLETE";
        case RoomState::CRASHING_PLATES_PLAYED: return "CRASHING_PLATES_PLAYED";
        case RoomState::SMART_FILM_REVEALED: return "SMART_FILM_REVEALED";
        case RoomState::COLOR_BUTTON_SEQUENCE_ACTIVE: return "COLOR_BUTTON_SEQUENCE_ACTIVE";
        case RoomState::COLOR_BUTTON_SEQUENCE_COMPLETE: return "COLOR_BUTTON_SEQUENCE_COMPLETE";
        case RoomState::DISPLAY_BAKE_350: return "DISPLAY_BAKE_350";
        case RoomState::OVEN_KNOB_ACTIVE: return "OVEN_KNOB_ACTIVE";
        case RoomState::OVEN_TARGET_REACHED: return "OVEN_TARGET_REACHED";
        case RoomState::ELECTROMAGNETIC_LOCK_RELEASED: return "ELECTROMAGNETIC_LOCK_RELEASED";
        case RoomState::ROOM_KEY_AVAILABLE: return "ROOM_KEY_AVAILABLE";
    }

    return "UNKNOWN";
}

#endif
