#!/usr/bin/env bash
set -euo pipefail

PROJECT_ROOT="${PROJECT_ROOT:-$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)}"
BASHRC="${BASHRC:-${HOME}/.bashrc}"
HELP_SNIPPET="${HOME}/.escape-room-help.sh"
START_MARKER="# >>> escape-room help command >>>"
END_MARKER="# <<< escape-room help command <<<"

cat >"${HELP_SNIPPET}" <<EOF
# Generated by ${PROJECT_ROOT}/tools/install-help-command.sh
# This intentionally overrides Bash's built-in "help" command for SSH sessions.
help() {
    local root="\${ESCAPE_ROOM_ROOT:-${PROJECT_ROOT}}"

    if [ -x "\${root}/tools/help.sh" ]; then
        "\${root}/tools/help.sh" "\$@"
        return
    fi

    echo "Escape room help is installed, but \${root}/tools/help.sh was not found."
    echo "Try this first:"
    echo "  cd escape-room"
    echo "  tools/rebase.sh"
}
EOF

touch "${BASHRC}"
tmp_file="$(mktemp)"
awk -v start="${START_MARKER}" -v end="${END_MARKER}" '
    $0 == start { skipping = 1; next }
    $0 == end { skipping = 0; next }
    skipping != 1 { print }
' "${BASHRC}" >"${tmp_file}"

cat >>"${tmp_file}" <<EOF
${START_MARKER}
if [ -f "${HELP_SNIPPET}" ]; then
    . "${HELP_SNIPPET}"
fi
${END_MARKER}
EOF

mv "${tmp_file}" "${BASHRC}"

echo "Installed escape-room help command for future SSH sessions."
echo "Use it now with:"
echo "  source ${HELP_SNIPPET}"
echo "  help"
